#!/usr/bin/env python3
# This file is part of Impulse, the retro music FPGA synthesizer.
# Copyright (c) 2022 Matt Young. All rights reserved.

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0

# Generates SystemVerilog code for converting MIDI note to a clock period

# System sampling rate in Hz
SAMPLING_RATE = 44100

def note2period(note):
    return float(SAMPLING_RATE) / (2.0**((note-69)/12.0) * 440.0)

if __name__ == "__main__":
    print("// Generated by scripts/gen_note_to_period.py")
    print("function logic [13:0] note_to_period(input logic [7:0] note);\n    begin")
    print("    case (note)")
    for i in range(127):
        print(f"        {i}: note_to_period = {int(note2period(i))};")
    print("        default: note_to_period = 0;")
    print("    endcase\n    end")
    print("endfunction")